USE master;

CREATE DATABASE Hotel;

USE Hotel;

CREATE TABLE Pokoj(ID INT CONSTRAINT PK PRIMARY KEY IDENTITY(1, 1), NumerPietra NCHAR(1) NOT NULL, NumerPokoju NCHAR(3) NOT NULL, 
Iluosobowy CHAR(1) DEFAULT 1, Koszt DECIMAL(6, 2) NOT NULL);

CREATE TABLE Gosc(ID INT CONSTRAINT PK1 PRIMARY KEY IDENTITY(1, 1), Imie NVARCHAR(60) NOT NULL, Nazwisko NVARCHAR(100) NOT NULL, 
Kraj VARCHAR(60) DEFAULT 'Polska', Telefon NVARCHAR(25) NOT NULL, Email NVARCHAR(50));

CREATE TABLE Rezerwacja(ID INT CONSTRAINT PK2 PRIMARY KEY IDENTITY(1, 1), DataZameldowania DATE NOT NULL, DataWymeldowania DATE NOT NULL, 
PokojID INT CONSTRAINT FK FOREIGN KEY REFERENCES Pokoj(ID) NOT NULL);

CREATE TABLE Pobyt(ID INT CONSTRAINT PK3 PRIMARY KEY IDENTITY(1, 1), RezerwacjaID INT CONSTRAINT FK1 FOREIGN KEY REFERENCES Rezerwacja(ID) NOT NULL, 
GoscID INT CONSTRAINT FK2 FOREIGN KEY REFERENCES Gosc(ID) NOT NULL);
