//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pobyt
    {
        public int ID { get; set; }
        public int RezerwacjaID { get; set; }
        public int GoscID { get; set; }
    
        public virtual Gosc Gosc { get; set; }
        public virtual Rezerwacja Rezerwacja { get; set; }
    }
}
